---
# Copyright Brandon B. Jozsa, v1k0d3n, Red Hat and other contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

## kubenode04
## Create libvirtGuestTemplate: kubenode31 on host galvatron01.jinkit.com
- hosts: galvatron01.jinkit.com
  gather_facts: false
  become: yes
  roles:
    - createAILibvirtGuestTemplates
  vars:
    # - clusterID: "{{ hostvars['DUMMY_HOST']['currentClusterID'] }}"
    - clusterID: "the"
    - libvirtHostName: "galvatron01.jinkit.com"
    - libvirtGuestName: "kubenode31"
    - dirRemoteLibvirtBase: "/opt/ocp-demos/libvirt/guests"
    - dirRemoteLibvirtBoot: "/var/lib/libvirt/boot"
    - dirRemoteLibvirtImages: "/var/lib/libvirt/images"
    - fileLocalISO: "./.clusters/${clusterID}/{{ clusterID }}.iso"
    - fileRemoteISO: "{{ dirRemoteLibvirtBoot }}/ai-discovery-{{ clusterID }}.iso"
    - fileRemoteLibvirtGuestLog: "{{ dirRemoteLibvirtBase }}/{{ libvirtGuestName }}/{{ libvirtGuestName }}.log"
    - libvirtGuestExecutionDelay: "8"
    - libvirtGuestVirtType: "kvm"
    - libvirtGuestComputeMemory: "16384"
    - libvirtGuestComputeVCPUs: "4"
    - libvirtGuestAccelerate: "True"
    - libvirtGuestAutoStart: "True"
    - libvirtGuestOSVariant: "rhel8.3"
    - libvirtGuestDiskCDROM: "/var/lib/libvirt/boot/ai-discovery-{{ clusterID }}.iso"
    - libvirtGuestDiskPath: "/var/lib/libvirt/images/{{ libvirtGuestName }}.qcow2"
    - libvirtGuestDiskSize: "120"
    - libvirtGuestDiskBus: "virtio"
    - libvirtGuestDiskFormat: "qcow2"
    - libvirtGuestNetworkMAC: "0e:00:00:03:60:31"
    - libvirtGuestNetworkBridge: "br60"
    - libvirtGuestNetworkModel: "virtio"
    - libvirtGuestGraphicsVNCPort: "5931"
    - libvirtGuestGraphicsVNCListen: "0.0.0.0"
    - libvirtGuestGraphicsVNCPassword: "redhat"

## kubenode05
## Create libvirtGuestTemplate: kubenode32 on host galvatron02.jinkit.com
- hosts: galvatron02.jinkit.com
  gather_facts: false
  become: yes
  roles:
    - createAILibvirtGuestTemplates
  vars:
    # - clusterID: "{{ hostvars['DUMMY_HOST']['currentClusterID'] }}"
    - clusterID: "the"
    - libvirtHostName: "galvatron02.jinkit.com"
    - libvirtGuestName: "kubenode32"
    - dirRemoteLibvirtBase: "/opt/ocp-demos/libvirt/guests"
    - dirRemoteLibvirtBoot: "/var/lib/libvirt/boot"
    - dirRemoteLibvirtImages: "/var/lib/libvirt/images"
    - fileLocalISO: "./.clusters/${clusterID}/{{ clusterID }}.iso"
    - fileRemoteISO: "{{ dirRemoteLibvirtBoot }}/ai-discovery-{{ clusterID }}.iso"
    - fileRemoteLibvirtGuestLog: "{{ dirRemoteLibvirtBase }}/{{ libvirtGuestName }}/{{ libvirtGuestName }}.log"
    - libvirtGuestExecutionDelay: "8"
    - libvirtGuestVirtType: "kvm"
    - libvirtGuestComputeMemory: "16384"
    - libvirtGuestComputeVCPUs: "4"
    - libvirtGuestAccelerate: "True"
    - libvirtGuestAutoStart: "True"
    - libvirtGuestOSVariant: "rhel8.3"
    - libvirtGuestDiskCDROM: "/var/lib/libvirt/boot/ai-discovery-{{ clusterID }}.iso"
    - libvirtGuestDiskPath: "/var/lib/libvirt/images/{{ libvirtGuestName }}.qcow2"
    - libvirtGuestDiskSize: "120"
    - libvirtGuestDiskBus: "virtio"
    - libvirtGuestDiskFormat: "qcow2"
    - libvirtGuestNetworkMAC: "0e:00:00:03:60:32"
    - libvirtGuestNetworkBridge: "br60"
    - libvirtGuestNetworkModel: "virtio"
    - libvirtGuestGraphicsVNCPort: "5932"
    - libvirtGuestGraphicsVNCListen: "0.0.0.0"
    - libvirtGuestGraphicsVNCPassword: "redhat"

## kubenode06
## Create libvirtGuestTemplate: kubenode33 on host galvatron03.jinkit.com
- hosts: galvatron03.jinkit.com
  gather_facts: false
  become: yes
  roles:
    - createAILibvirtGuestTemplates
  vars:
    # - clusterID: "{{ hostvars['DUMMY_HOST']['currentClusterID'] }}"
    - clusterID: "the"
    - libvirtHostName: "galvatron03.jinkit.com"
    - libvirtGuestName: "kubenode33"
    - dirRemoteLibvirtBase: "/opt/ocp-demos/libvirt/guests"
    - dirRemoteLibvirtBoot: "/var/lib/libvirt/boot"
    - dirRemoteLibvirtImages: "/var/lib/libvirt/images"
    - fileLocalISO: "./.clusters/${clusterID}/{{ clusterID }}.iso"
    - fileRemoteISO: "{{ dirRemoteLibvirtBoot }}/ai-discovery-{{ clusterID }}.iso"
    - fileRemoteLibvirtGuestLog: "{{ dirRemoteLibvirtBase }}/{{ libvirtGuestName }}/{{ libvirtGuestName }}.log"
    - libvirtGuestExecutionDelay: "8"
    - libvirtGuestVirtType: "kvm"
    - libvirtGuestComputeMemory: "16384"
    - libvirtGuestComputeVCPUs: "4"
    - libvirtGuestAccelerate: "True"
    - libvirtGuestAutoStart: "True"
    - libvirtGuestOSVariant: "rhel8.3"
    - libvirtGuestDiskCDROM: "/var/lib/libvirt/boot/ai-discovery-{{ clusterID }}.iso"
    - libvirtGuestDiskPath: "/var/lib/libvirt/images/{{ libvirtGuestName }}.qcow2"
    - libvirtGuestDiskSize: "120"
    - libvirtGuestDiskBus: "virtio"
    - libvirtGuestDiskFormat: "qcow2"
    - libvirtGuestNetworkMAC: "0e:00:00:03:60:33"
    - libvirtGuestNetworkBridge: "br60"
    - libvirtGuestNetworkModel: "virtio"
    - libvirtGuestGraphicsVNCPort: "5933"
    - libvirtGuestGraphicsVNCListen: "0.0.0.0"
    - libvirtGuestGraphicsVNCPassword: "redhat"

# clusterID: "622fa8ca-e797-4185-8230-b40ebcb6187b"
# libvirtGuestName: kubenode24
# dirRemoteLibvirtBase: /opt/ocp-demos/libvirt/guests
# dirRemoteLibvirtBoot: /var/lib/libvirt/boot
# dirRemoteLibvirtImages: /var/lib/libvirt/images
# fileLocalISO: ./.clusters/{{ clusterID }}/{{ clusterID }}.iso
# fileRemoteISO: "{{ dirRemoteLibvirtBoot }}/ai-discovery-{{ clusterID }}.iso"
# fileRemoteLibvirtGuestLog: "{{ dirRemoteLibvirtBase }}/{{ libvirtGuestName }}/{{ libvirtGuestName }}.log"



# - hosts: libvirtOCPTesting
#   collections:
#     - community.libvirt.virt
#   gather_facts: false
#   become: yes
#   roles:
#     - startAILibvirtGuest