---
# Copyright v1kod3n, and other 'ansible-os-traveling-circus' contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Only here for testing purposes:
# - hosts: assistedInstaller
#   gather_facts: false
#   roles: 
#     - testPing

- hosts: assistedInstaller
  gather_facts: false
  become: yes
  roles: 
    - installPodman

- hosts: assistedInstaller
  collections:
    - containers.podman
  gather_facts: false
  become: yes
  roles:
    - deleteAssistedInstaller
  vars:
    - forceClean: false

- hosts: assistedInstaller
  collections:
    - containers.podman
  gather_facts: true
  become: yes
  roles:
    - configureAssistedInstaller
  vars:
    - RHCOS_LIVEISO_CHK: "b264d398cce0affca218ee56808332d90b7c0a6dac2c061effdfa834a86623ba"