---
# Copyright Brandon B. Jozsa, v1k0d3n, Red Hat and other contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Instructions: 
# Edit the variables below for each of the libvirtGuests, hosts, the 
# Assisted Installer API endpoint, and the clusterID.
#

- name: test to ensure that hosts are alive
  ping:

- name: Assisted Installer - delete installer container
  tags: [deleteAI]
  containers.podman.podman_container:
    name: installer
    state: absent

- name: Assisted Installer - delete installer container
  tags: [deleteAI]
  containers.podman.podman_container:
    name: ui
    state: absent

- name: Assisted Installer - delete installer container
  tags: [deleteAI]
  containers.podman.podman_container:
    name: db
    state: absent

- name: Assisted Installer - delete installer container
  tags: [deleteAI]
  containers.podman.podman_pod:
    name: assisted-installer
    state: absent
